### PR TITLE
validate monero addresses based on network

### LINKED ISSUE #136: validate externally submitted xmr addresses based on network
eg. when swapping from the ui, if the wrong type of address is used, the swap will not error with the right error as address validation based on network is not happening immediately.

### PR DESCRIPTION
**Pull request by noot**
closes #136

### CODE REVIEW

File: crypto/monero/address.go [hunk 1]
```diff
@@ -15,15 +15,31 @@ const (
...
+
+	switch env {
+	case common.Mainnet, common.Development:
+		if b[0] != addressPrefixMainnet {
+			return errInvalidPrefixGotStagenet
+		}
+	case common.Stagenet:
+		if b[0] != addressPrefixStagenet {
+			return errInvalidPrefixGotMainnet
+		}
```
Comment (dimalinux) [inline crypto/monero/address.go:42]: After the PR enabling the full wallet API, this will be another option:
https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#validate_address
