### PR TITLE
store swap recovery information in database, remove "infofile"

### LINKED ISSUE #202: deprecate `contract-addresses.json`
currently, if swapd deploys a swap contract (for testing purposes) it gets written to `contract-address.json`. however, this isn't really needed, as contract addresses used in swaps are stored in the swap info file.

### LINKED ISSUE #203: store info file contents in database
the info file contains information needed to recover swap funds in case of a swapd crash (after funds are locked but before they are claimed). currently, it's just stored in a json file that's written to disk. however, this info can be stored in the database instead now that we have one, and cleared out upon swap completion.

this will also allow for `swapcli` functionality to be built that allows users to easily query for completed vs. ongoing swaps.

### PR DESCRIPTION
**Pull request by noot**
as title says, also:
- implement `RecoveryDB` for storing the info instead
- note: this PR removes the `swaprecover` binary as I couldn't be bothered to fix it as it's going to be removed in a follow up (#212)

closes #203

### CODE REVIEW

File: rpcclient/wsclient/wsclient.go [hunk 1]
```diff
@@ -255,26 +255,35 @@ func (c *wsClient) TakeOfferAndSubscribe(multiaddr, offerID string,
 		return nil, err
 	}
 
-	// read ID from connection
-	message, err := c.read()
-	if err != nil {
-		return nil, fmt.Errorf("failed to read websockets message: %s", err)
-	}
+	readMessageFn := func() (string, error) {
```
Comment (dimalinux) [inline rpcclient/wsclient/wsclient.go:258]: `TakeOfferAndSubscribe` is 172 lines lines. Maybe we could pull this code out into it's own function and then the code auditor doesn't have to carefully read it to understand which variables are shared with the outer scope?

File: protocol/xmrmaker/net.go [hunk 2]
```diff
@@ -73,6 +70,9 @@ func (b *Instance) initiate(
 
 // HandleInitiateMessage is called when we receive a network message from a peer that they wish to initiate a swap.
 func (b *Instance) HandleInitiateMessage(msg *net.SendKeysMessage) (net.SwapState, net.Message, error) {
+	b.swapMu.Lock()
+	defer b.swapMu.Unlock()
```
Comment (dimalinux) [inline protocol/xmrmaker/net.go:74]: So these were the missing lines that were needed to prevent the race condition when 2 parties try to take the same offer simultaneously?

Comment (noot) [reply protocol/xmrmaker/net.go:74]: maybe, I don't think it fully fixes it, I think the issue is more how the test is written or another issue - when I looked at the logs, the issue was that one of the takers was hanging.

File: db/recovery_db.go [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+	return db.db.Put(key[:], val)
+}
+
+// PutContractSwapInfo stores the given contract swap ID (which is not the same as the daemon
+// swap ID, but is instead a hash of the `SwapFactorySwap` structure)
+// and contract swap structure for the given swap ID.
+func (db *RecoveryDB) PutContractSwapInfo(id types.Hash, swapID [32]byte, swap contracts.SwapFactorySwap) error {
+	val, err := json.Marshal(&struct {
+		SwapID [32]byte
+		Swap   contracts.SwapFactorySwap
```
Comment (dimalinux) [inline db/recovery_db.go:69]: Can we pull this out, give it the semantic version field, add JSON annotations, use a hash type that will auto-serialize as hex, and add at least one unit test for the JSON marshaling so you can see what the JSON looks like when reading the code? I is a little painful, but the odds of the format never changing are probably low. Having the ID in hex will help us troubleshoot. I can update the PR later today if you want.

File: rpcclient/wsclient/wsclient.go (hunk 1 above)
Comment (noot) [reply rpcclient/wsclient/wsclient.go]: updated!

File: protocol/xmrtaker/recovery.go [hunk 4]
```diff
@@ -57,7 +56,6 @@ func NewRecoveryState(b backend.Backend, dataDir string, secret *mcrypto.Private
 		walletScanHeight: 0, // TODO: Can we optimise this?
```
[the remark this answers is not in the document]
Comment (noot) [reply protocol/xmrtaker/recovery.go:56]: yeah, I realized when trying to implement another issue we need the eth start height as well, will add

File: db/recovery_db.go (hunk 3 above)
Comment (noot) [reply db/recovery_db.go]: updated, but I'm not sure if I see the point of adding the version necessarily since this info is likely not going to be persisted long-term - it's only stored while a swap is ongoing, and will end up being deleted after

Comment (dimalinux) [reply db/recovery_db.go]: Yeah, then it isn't needed. I thought a swap might be created with one version of `swapd` and might possibly be recovered by a newer `swapd` version.  I didn't add it in `dimalinux/db-swap-info-json`.

File: db/types.go [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+
+	"github.com/athanorlabs/atomic-swap/common/types"
+	contracts "github.com/athanorlabs/atomic-swap/ethereum"
+
+	ethcommon "github.com/ethereum/go-ethereum/common"
+)
+
+// EthereumSwapInfo represents information required on the Ethereum side in case of recovery
+type EthereumSwapInfo struct {
+	StartNumber     *big.Int                  `json:"startNumber"`
```
Comment (dimalinux) [inline db/types.go:14]: Can we document and, if appropriate, rename this field?  Is it the block number of the `newSwap` transaction? Is it the same for the maker and the taker? I wanted to rename it in `dimalinux/db-swap-info-json`, but I didn't know what it was without digging, so I left it.

**Review by dimalinux — APPROVED** [review]
Looks good. I provided a PR with human friendly JSON serialization of `SwapFactorySwap` for merging into this PR's branch. I also left one last comment/request about the `StartNumber` field of `EthereumSwapInfo` in this PR.

File: db/types.go (hunk 5 above)
Comment (noot) [reply db/types.go]: yeah it's the block number of the `newSwap`  tx, is the same for both, will update
